### ISSUE TITLE
Add Catholic Feast days and events notification/calendar

### ISSUE THREAD

**Issue by AndreaGon** [AndreaGon/IchthysBot#5]
Roman Catholic Liturgical Calendar: http://calapi.inadiutorium.cz/api-doc

**Comment by SeanActon** [comment]
Hey I think I may start contributing to this, I wanted to add functionality for Catechism paragraphs and have it work inside discord threads. Is this still being worked on?

**Comment by AndreaGon** [comment]
Hi there, feel free to start working on this :) I am currently focusing on refactoring some of the code to make it easier to add features in the future.
